// packages/timescope-react/App.tsx
import { Decimal, Timescope } from '@timescope/react';
import { useState } from 'react';
import { type TimescopeRange } from 'timescope';

function App() {
  const [time, setTime] = useState<Decimal | null>(null);
  const [timeChanging, setTimeChanging] = useState<Decimal | null>(null);
  const [timeAnimating, setTimeAnimating] = useState<Decimal | null>(null);
  const [selectedRangeChanging, setSelectedRangeChanging] = useState<TimescopeRange<Decimal> | null>(null);

  return (
    <>
      <Timescope
        time={time}
        onTimeChanged={setTime}
        onTimeChanging={setTimeChanging}
        onTimeAnimating={setTimeAnimating}
        onSelectedRangeChanging={setSelectedRangeChanging}
      />
      <pre>time: {time?.toString()}</pre>
      <pre>timeChanging: {timeChanging?.toString()}</pre>
      <pre>timeAnimating: {timeAnimating?.toString()}</pre>
      <pre>selectedRangeChanging: {selectedRangeChanging?.toString()}</pre>
    </>
  );
}

export default App;

// packages/timescope-solid/playground/src/App.tsx
import { createSignal } from 'solid-js';
import { Decimal, type TimescopeRange } from 'timescope';
import { Timescope } from '../../src';

export function App() {
  const [time, setTime] = createSignal<Decimal | null>(null);
  const [zoom] = createSignal<number>(-22);
  const [timeAnimating, setTimeAnimating] = createSignal<Decimal | null>(null);
  const [timeChanging, setTimeChanging] = createSignal<Decimal | null>(null);
  const [selectedRangeChanged, setSelectedRangeChanged] = createSignal<TimescopeRange<Decimal> | null>(null);
  const [selectedRangeChanging, setSelectedRangeChanging] = createSignal<TimescopeRange<Decimal> | null>(null);

  return (
    <>
      <Timescope
        time={time()}
        zoom={zoom()}
        selectedRange={selectedRangeChanged()}
        onTimeAnimating={setTimeAnimating}
        onTimeChanging={setTimeChanging}
        onTimeChanged={setTime}
        onSelectedRangeChanged={setSelectedRangeChanged}
        onSelectedRangeChanging={setSelectedRangeChanging}
      />
      <pre>
        time: {time()?.toString()}
        <br />
        timeChanging: {timeChanging()?.toString()}
        <br />
        timeAnimating: {timeAnimating()?.toString()}
        <br />
        selectedRangeChanging: {selectedRangeChanging()?.toString()}
        <br />
      </pre>
    </>
  );
}
