// packages/timescope-svelte/src/lib/Timescope.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import type {
    Decimal,
    TimescopeOptions,
    TimescopeOptionsInitial,
    TimescopeOptionsSelection,
    TimescopeRange,
    TimescopeSeriesInput,
    TimescopeSourceInput,
  } from 'timescope';
  import { Timescope } from 'timescope';

  export type TimescopeProps = {
    width?: string;
    height?: string;
    background?: string;

    time?: Decimal | number | null | string | Date;
    timeRange?: [
      Decimal | number | null | string | Date | undefined,
      Decimal | number | null | string | Date | undefined,
    ];
    zoom?: number;
    zoomRange?: [number | undefined, number | undefined];

    sources?: TimescopeOptions['sources'];
    series?: TimescopeOptions['series'];
    tracks?: TimescopeOptions['tracks'];

    indicator?: boolean;
    selection?: TimescopeOptionsSelection;

    selectionRange?: TimescopeRange<Decimal> | null;

    showFps?: boolean;
    renderThread?: TimescopeOptions['renderThread'];

    fonts?: TimescopeOptionsInitial<
      Record<string, TimescopeSourceInput>,
      Record<string, TimescopeSeriesInput>,
      string
    >['fonts'];
  };

  type TimescopeEvents = {
    timechanged: Decimal | null;
    timechanging: Decimal | null;
    timeanimating: Decimal | null;
    zoomchanged: number;
    zoomchanging: number;
    zoomanimating: number;
    selectionrangechanging: [Decimal, Decimal] | null;
    selectionrangechanged: [Decimal, Decimal] | null;
    animating: boolean;
    editing: boolean;
  };

  let {
    width = '100%',
    height = '36px',
    background,
    time = $bindable<Decimal | number | null | string | Date | undefined>(undefined),
    timeRange,
    zoom = $bindable<number | undefined>(undefined),
    zoomRange,
    sources,
    series,
    tracks,
    indicator = true,
    selection,
    selectionRange = $bindable<TimescopeRange<Decimal> | null | undefined>(undefined),
    showFps,
    renderThread,
    fonts,
  } = $props<TimescopeProps>();

  const dispatch = createEventDispatcher<TimescopeEvents>();

  let container: HTMLDivElement | null = null;
  let timescope: Timescope | null = null;

  onMount(() => {
    timescope = new Timescope({
      renderThread,
      time: time ?? null,
      timeRange,
      zoom: zoom ?? 0,
      zoomRange,
      fonts,
    });

    timescope.on('timechanging', (e) => dispatch('timechanging', e.value));
    timescope.on('timechanged', (e) => {
      time = e.value;
      dispatch('timechanged', e.value);
    });
    timescope.on('timeanimating', (e) => dispatch('timeanimating', e.value));
    timescope.on('zoomchanging', (e) => dispatch('zoomchanging', e.value));
    timescope.on('zoomchanged', (e) => {
      zoom = e.value;
      dispatch('zoomchanged', e.value);
    });
    timescope.on('zoomanimating', (e) => dispatch('zoomanimating', e.value));
    timescope.on('selectionrangechanging', (e) => dispatch('selectionrangechanging', e.value));
    timescope.on('selectionrangechanged', (e) => {
      selectionRange = e.value;
      dispatch('selectionrangechanged', e.value);
    });

    let animating = timescope.animating;
    let editing = timescope.editing;
    timescope.on('change', () => {
      if (timescope?.animating !== animating) {
        animating = timescope?.animating ?? false;
        dispatch('animating', animating);
      }
      if (timescope?.editing !== editing) {
        editing = timescope?.editing ?? false;
        dispatch('editing', editing);
      }
    });

    return () => {
      timescope?.dispose();
      timescope = null;
    };
  });

  $effect(() => {
    if (!timescope || !container) return;
    timescope.mount(container);
    return () => timescope?.unmount();
  });

  $effect(() => {
    if (!timescope) return;
    if (time !== undefined) timescope.setTime(time ?? null);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.setTimeRange(timeRange);
  });

  $effect(() => {
    if (!timescope) return;
    if (zoom !== undefined) timescope.setZoom(zoom ?? 0);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.setZoomRange(zoomRange);
  });

  $effect(() => {
    if (!timescope) return;
    if (selectionRange !== undefined) timescope.setSelectionRange(selectionRange ?? null);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ style: { width, height, background } });
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ sources } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ series } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ tracks } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ indicator } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ selection } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ showFps, renderThread } as TimescopeOptions);
  });

  export function setTime(...args: Parameters<Timescope['setTime']>) {
    return timescope?.setTime(...args) ?? false;
  }

  export function setZoom(...args: Parameters<Timescope['setZoom']>) {
    return timescope?.setZoom(...args) ?? false;
  }

  export function fitTo(...args: Parameters<Timescope['fitTo']>) {
    return timescope?.fitTo(...args) ?? false;
  }
</script>

<div bind:this={container}></div>

// packages/timescope-solid/src/Timescope.tsx
import type { Decimal } from '@kikuchan/decimal';
import { createEffect, onCleanup, untrack } from 'solid-js';
import {
  Timescope,
  TimescopeOptions,
  TimescopeOptionsInitial,
  TimescopeOptionsSelection,
  TimescopeOptionsSeries,
  TimescopeOptionsSources,
  TimescopeOptionsTracks,
  TimescopeRange,
  TimescopeSeriesInput,
  TimescopeSourceInput,
} from 'timescope';

type TimescopeProps<
  Sources extends Record<string, TimescopeSourceInput>,
  Series extends Record<string, TimescopeSeriesInput>,
  Track extends string,
> = {
  width?: string;
  height?: string;
  background?: string;

  time?: Decimal | number | null | string | Date;
  timeRange?: [
    Decimal | number | null | string | Date | undefined,
    Decimal | number | null | string | Date | undefined,
  ];
  zoom?: number;
  zoomRange?: [number | undefined, number | undefined];

  sources?: TimescopeOptionsSources<Sources>;
  series?: TimescopeOptionsSeries<Sources, Series, Track>;
  tracks?: TimescopeOptionsTracks<Track>;

  indicator?: boolean;
  selection?: TimescopeOptionsSelection;

  selectionRange?: TimescopeRange<Decimal> | null;

  showFps?: boolean;
  renderThread?: TimescopeOptions['renderThread'];

  fonts?: TimescopeOptionsInitial<Sources, Series, Track>['fonts'];

  onTimeAnimating?: (v: Decimal | null) => void;
  onTimeChanging?: (v: Decimal | null) => void;
  onTimeChanged?: (v: Decimal | null) => void;
  onZoomAnimating?: (v: number) => void;
  onZoomChanging?: (v: number) => void;
  onZoomChanged?: (v: number) => void;
  onSelectionRangeChanging?: (v: TimescopeRange<Decimal> | null) => void;
  onSelectionRangeChanged?: (v: TimescopeRange<Decimal> | null) => void;
  onAnimating?: (v: boolean) => void;
  onEditing?: (v: boolean) => void;
  style?: any;
  class?: any;
};

function TimescopeComponent<
  Sources extends Record<string, TimescopeSourceInput>,
  Series extends Record<string, TimescopeSeriesInput>,
  Track extends string,
>(props: TimescopeProps<Sources, Series, Track>) {
  const timescope = new Timescope({
    renderThread: untrack(() => props.renderThread),
    time: untrack(() => props.time ?? null),
    timeRange: untrack(() => props.timeRange),
    zoom: untrack(() => props.zoom ?? 0),
    zoomRange: untrack(() => props.zoomRange),
    fonts: untrack(() => props.fonts),
  });

  createEffect(() => {
    const onTimeAnimating = props.onTimeAnimating;
    const onTimeChanging = props.onTimeChanging;
    const onTimeChanged = props.onTimeChanged;
    const onZoomAnimating = props.onZoomAnimating;
    const onZoomChanging = props.onZoomChanging;
    const onZoomChanged = props.onZoomChanged;
    const onSelectionRangeChanging = props.onSelectionRangeChanging;
    const onSelectionRangeChanged = props.onSelectionRangeChanged;
    const onAnimating = props.onAnimating;
    const onEditing = props.onEditing;

    const uns = [
      timescope.on('timeanimating', (e) => onTimeAnimating?.(e.value)),
      timescope.on('timechanging', (e) => onTimeChanging?.(e.value)),
      timescope.on('timechanged', (e) => onTimeChanged?.(e.value)),
      timescope.on('zoomanimating', (e) => onZoomAnimating?.(e.value)),
      timescope.on('zoomchanging', (e) => onZoomChanging?.(e.value)),
      timescope.on('zoomchanged', (e) => onZoomChanged?.(e.value)),
      timescope.on('selectionrangechanging', (e) => onSelectionRangeChanging?.(e.value)),
      timescope.on('selectionrangechanged', (e) => onSelectionRangeChanged?.(e.value)),
    ];

    let animating = timescope.animating;
    let editing = timescope.editing;
    uns.push(
      timescope.on('change', () => {
        if (timescope.animating !== animating) {
          animating = timescope.animating;
          onAnimating?.(animating);
        }
        if (timescope.editing !== editing) {
          editing = timescope.editing;
          onEditing?.(editing);
        }
      }),
    );

    onCleanup(() => {
      for (const un of uns) un();
    });
  });

  createEffect(() => {
    if (props.time !== undefined) timescope.setTime(props.time);
  });
  createEffect(() => {
    timescope.setTimeRange(props.timeRange);
  });
  createEffect(() => {
    if (props.zoom !== undefined) timescope.setZoom(props.zoom);
  });
  createEffect(() => {
    timescope.setZoomRange(props.zoomRange);
  });
  createEffect(() => {
    if (props.selectionRange !== undefined) timescope.setSelectionRange(props.selectionRange);
  });
  createEffect(() => {
    timescope.updateOptions({
      style: { width: props.width ?? '100%', height: props.height ?? '36px', background: props.background },
    });
  });
  createEffect(() => {
    timescope.updateOptions({ sources: props.sources } as TimescopeOptions);
  });
  createEffect(() => {
    timescope.updateOptions({ series: props.series } as TimescopeOptions);
  });
  createEffect(() => {
    timescope.updateOptions({ tracks: props.tracks } as TimescopeOptions);
  });
  createEffect(() => {
    timescope.updateOptions({ indicator: props.indicator ?? true } as TimescopeOptions);
  });
  createEffect(() => {
    timescope.updateOptions({ selection: props.selection } as TimescopeOptions);
  });
  createEffect(() => {
    timescope.updateOptions({ showFps: props.showFps, renderThread: props.renderThread } as TimescopeOptions);
  });

  onCleanup(() => {
    timescope.dispose();
  });

  return (
    <div
      class={props.class}
      style={props.style}
      ref={(e) => {
        timescope.unmount();
        if (e) timescope.mount(e);
      }}
    />
  );
}

export { TimescopeComponent as default, TimescopeComponent as Timescope };
