// packages/timescope-solid/playground/src/App.tsx
import { createSignal } from 'solid-js';
import { Decimal, type TimescopeRange } from 'timescope';
import { Timescope } from '../../src';

const options = { style: { height: '80px' } };

export function App() {
  const [time, setTime] = createSignal<Decimal | null>(null);
  const [zoom] = createSignal<number>(-22);
  const [timeAnimating, setTimeAnimating] = createSignal<Decimal | null>(null);
  const [timeChanging, setTimeChanging] = createSignal<Decimal | null>(null);
  const [selectionRange, setSelectionRange] = createSignal<TimescopeRange<Decimal> | null>(null);
  const [selectionRangeChanging, setSelectionRangeChanging] = createSignal<TimescopeRange<Decimal> | null>(null);

  return (
    <>
      <Timescope
        options={options}
        time={time()}
        zoom={zoom()}
        selectionRange={selectionRange()}
        onTimeAnimating={setTimeAnimating}
        onTimeChanging={setTimeChanging}
        onTimeChanged={setTime}
        onSelectionRangeChanged={setSelectionRange}
        onSelectionRangeChanging={setSelectionRangeChanging}
      />
      <pre>
        time: {time()?.toString()}
        <br />
        timeChanging: {timeChanging()?.toString()}
        <br />
        timeAnimating: {timeAnimating()?.toString()}
        <br />
        selectionRangeChanging: {selectionRangeChanging()?.toString()}
        <br />
      </pre>
    </>
  );
}

// packages/timescope-react/playground/App.tsx
import { Decimal, Timescope } from '@timescope/react';
import { useState } from 'react';
import { type TimescopeRange } from 'timescope';

const options = { style: { height: '80px' } };

function App() {
  const [time, setTime] = useState<Decimal | null>(null);
  const [timeChanging, setTimeChanging] = useState<Decimal | null>(null);
  const [timeAnimating, setTimeAnimating] = useState<Decimal | null>(null);
  const [selectionRangeChanging, setSelectionRangeChanging] = useState<TimescopeRange<Decimal> | null>(null);

  return (
    <>
      <Timescope
        options={options}
        time={time}
        onTimeChanged={setTime}
        onTimeChanging={setTimeChanging}
        onTimeAnimating={setTimeAnimating}
        onSelectionRangeChanging={setSelectionRangeChanging}
      />
      <pre>time: {time?.toString()}</pre>
      <pre>timeChanging: {timeChanging?.toString()}</pre>
      <pre>timeAnimating: {timeAnimating?.toString()}</pre>
      <pre>selectionRangeChanging: {selectionRangeChanging?.toString()}</pre>
    </>
  );
}

export default App;
