// packages/timescope-svelte/src/lib/Timescope.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import type {
    Decimal,
    TimescopeOptions,
    TimescopeOptionsInitial,
    TimescopeOptionsSelection,
    TimescopeRange,
    TimescopeSeriesInput,
    TimescopeSourceInput,
  } from 'timescope';
  import { Timescope } from 'timescope';

  export type TimescopeProps = {
    width?: string;
    height?: string;
    background?: string;

    time?: Decimal | number | null | string | Date;
    timeRange?: [
      Decimal | number | null | string | Date | undefined,
      Decimal | number | null | string | Date | undefined,
    ];
    zoom?: number;
    zoomRange?: [number | undefined, number | undefined];

    sources?: TimescopeOptions['sources'];
    series?: TimescopeOptions['series'];
    tracks?: TimescopeOptions['tracks'];

    indicator?: boolean;
    selection?: TimescopeOptionsSelection;

    selectedRange?: TimescopeRange<Decimal> | null;

    showFps?: boolean;

    fonts?: TimescopeOptionsInitial<
      Record<string, TimescopeSourceInput>,
      Record<string, TimescopeSeriesInput>,
      string
    >['fonts'];
  };

  type TimescopeEvents = {
    timechanged: Decimal | null;
    timechanging: Decimal | null;
    timeanimating: Decimal | null;
    zoomchanged: number;
    zoomchanging: number;
    zoomanimating: number;
    selectedrangechanging: [Decimal, Decimal] | null;
    selectedrangechanged: [Decimal, Decimal] | null;
    animating: boolean;
    editing: boolean;
  };

  let {
    width = '100%',
    height = '36px',
    background,
    time = $bindable<Decimal | number | null | string | Date | undefined>(undefined),
    timeRange,
    zoom = $bindable<number | undefined>(undefined),
    zoomRange,
    sources,
    series,
    tracks,
    indicator = true,
    selection,
    selectedRange = $bindable<TimescopeRange<Decimal> | null | undefined>(undefined),
    showFps,
    fonts,
  } = $props<TimescopeProps>();

  const dispatch = createEventDispatcher<TimescopeEvents>();

  let container: HTMLDivElement | null = null;
  let timescope: Timescope | null = null;

  onMount(() => {
    timescope = new Timescope({
      time: time ?? null,
      timeRange,
      zoom: zoom ?? 0,
      zoomRange,
      fonts,
    });

    timescope.on('timechanging', (e) => dispatch('timechanging', e.value));
    timescope.on('timechanged', (e) => {
      time = e.value;
      dispatch('timechanged', e.value);
    });
    timescope.on('timeanimating', (e) => dispatch('timeanimating', e.value));
    timescope.on('zoomchanging', (e) => dispatch('zoomchanging', e.value));
    timescope.on('zoomchanged', (e) => {
      zoom = e.value;
      dispatch('zoomchanged', e.value);
    });
    timescope.on('zoomanimating', (e) => dispatch('zoomanimating', e.value));
    timescope.on('selectedrangechanging', (e) => dispatch('selectedrangechanging', e.value));
    timescope.on('selectedrangechanged', (e) => {
      selectedRange = e.value;
      dispatch('selectedrangechanged', e.value);
    });

    let animating = timescope.animating;
    let editing = timescope.editing;
    timescope.on('change', () => {
      if (timescope?.animating !== animating) {
        animating = timescope?.animating ?? false;
        dispatch('animating', animating);
      }
      if (timescope?.editing !== editing) {
        editing = timescope?.editing ?? false;
        dispatch('editing', editing);
      }
    });

    return () => {
      timescope?.dispose();
      timescope = null;
    };
  });

  $effect(() => {
    if (!timescope || !container) return;
    timescope.mount(container);
    return () => timescope?.unmount();
  });

  $effect(() => {
    if (!timescope) return;
    if (time !== undefined) timescope.setTime(time ?? null);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.setTimeRange(timeRange);
  });

  $effect(() => {
    if (!timescope) return;
    if (zoom !== undefined) timescope.setZoom(zoom ?? 0);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.setZoomRange(zoomRange);
  });

  $effect(() => {
    if (!timescope) return;
    if (selectedRange !== undefined) timescope.setSelectedRange(selectedRange ?? null);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ style: { width, height, background } });
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ sources } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ series } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ tracks } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ indicator } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ selection } as TimescopeOptions);
  });

  $effect(() => {
    if (!timescope) return;
    timescope.updateOptions({ showFps } as TimescopeOptions);
  });

  export function setTime(...args: Parameters<Timescope['setTime']>) {
    return timescope?.setTime(...args) ?? false;
  }

  export function setZoom(...args: Parameters<Timescope['setZoom']>) {
    return timescope?.setZoom(...args) ?? false;
  }

  export function fitTo(...args: Parameters<Timescope['fitTo']>) {
    return timescope?.fitTo(...args) ?? false;
  }
</script>

<div bind:this={container}></div>

// packages/timescope-vue/src/Timescope.vue
<template>
  <div ref="container-ref"></div>
</template>

<script
  lang="ts"
  setup
  generic="
    Sources extends Record<string, TimescopeSourceInput>,
    Series extends Record<string, TimescopeSeriesInput>,
    Track extends string
  ">
import type {
  TimescopeOptions,
  TimescopeOptionsInitial,
  TimescopeOptionsSelection,
  TimescopeOptionsSeries,
  TimescopeOptionsSources,
  TimescopeOptionsTracks,
  TimescopeRange,
  TimescopeSeriesInput,
  TimescopeSourceInput,
} from 'timescope';
import { Timescope } from 'timescope';
import type { Decimal } from '@kikuchan/decimal';
import { customRef, markRaw, onBeforeUnmount, useTemplateRef, watch } from 'vue';

const emit = defineEmits<{
  timechanged: [Decimal | null];
  timechanging: [Decimal | null];
  timeanimating: [Decimal | null];
  zoomchanged: [number];
  zoomchanging: [number];
  zoomanimating: [number];
  selectedrangechanging: [[Decimal, Decimal] | null];
  selectedrangechanged: [[Decimal, Decimal] | null];
  animating: [boolean];
  editing: [boolean];

  'update:time': [Decimal | null];
  'update:zoom': [number];
  'update:timechanging': [Decimal | null];
  'update:zoomchanging': [number];
  'update:timeanimating': [Decimal | null];
  'update:zoomanimating': [number];
  'update:selectedrange': [[Decimal, Decimal] | null];
  'update:selectedrangechanging': [[Decimal, Decimal] | null];
}>();

const props = withDefaults(
  defineProps<{
    width?: string;
    height?: string;
    background?: string;

    time?: Decimal | number | null | string | Date;
    timeRange?: [
      Decimal | number | null | string | Date | undefined,
      Decimal | number | null | string | Date | undefined,
    ];
    zoom?: number;
    zoomRange?: [number | undefined, number | undefined];

    sources?: TimescopeOptionsSources<Sources>;
    series?: TimescopeOptionsSeries<Sources, Series, Track>;
    tracks?: TimescopeOptionsTracks<Track>;

    indicator?: boolean;
    selection?: TimescopeOptionsSelection;

    selectedRange?: TimescopeRange<Decimal> | null;

    showFps?: boolean;

    fonts?: TimescopeOptionsInitial<Sources, Series, Track>['fonts'];
  }>(),
  {
    width: '100%',
    height: '36px',
    indicator: true,
    selection: undefined,
  },
);

type Combination =
  | ['timechanged', 'time']
  | ['timechanging', 'timeChanging']
  | ['timeanimating', 'timeAnimating']
  | ['zoomchanged', 'zoom']
  | ['zoomchanging', 'zoomChanging']
  | ['zoomanimating', 'zoomAnimating']
  | ['change', 'animating']
  | ['change', 'editing']
  | ['selectedrangechanging', 'selectedRangeChanging']
  | ['selectedrangechanged', 'selectedRange'];

function createTimescopeRef<T extends Combination>(...args: T) {
  return customRef<typeof timescope[T[1]]>((track, trigger) => {
    timescope.on(args[0], () => trigger());
    return {
      get() {
        track();
        return timescope[args[1]] as typeof timescope[T[1]];
      },
      set() {
      },
    }
  });
}

const timescope = markRaw(
  new Timescope({
    time: props.time ?? null,
    timeRange: props.timeRange,
    zoom: props.zoom ?? 0,
    zoomRange: props.zoomRange,

    fonts: props.fonts,
  }),
);

defineExpose({
  time: createTimescopeRef('timechanged', 'time'),
  timeChanging: createTimescopeRef('timechanging', 'timeChanging'),
  timeAnimating: createTimescopeRef('timeanimating', 'timeAnimating'),
  zoom: createTimescopeRef('zoomchanged', 'zoom'),
  zoomChanging: createTimescopeRef('zoomchanging', 'zoomChanging'),
  zoomAnimating: createTimescopeRef('zoomanimating', 'zoomAnimating'),
  selectedRange: createTimescopeRef('selectedrangechanged', 'selectedRange'),
  selectedRangeChanging: createTimescopeRef('selectedrangechanging', 'selectedRangeChanging'),

  animating: createTimescopeRef('change', 'animating'),
  editing: createTimescopeRef('change', 'editing'),

  setTime: timescope.setTime.bind(timescope),
  setZoom: timescope.setZoom.bind(timescope),
  fitTo: timescope.fitTo.bind(timescope),
});

timescope.on('timechanging', (e) => emit('timechanging', e.value));
timescope.on('timechanged', (e) => emit('timechanged', e.value));
timescope.on('timeanimating', (e) => emit('timeanimating', e.value));
timescope.on('zoomchanging', (e) => emit('zoomchanging', e.value));
timescope.on('zoomchanged', (e) => emit('zoomchanged', e.value));
timescope.on('zoomanimating', (e) => emit('zoomanimating', e.value));
timescope.on('selectedrangechanging', (e) => emit('selectedrangechanging', e.value));
timescope.on('selectedrangechanged', (e) => emit('selectedrangechanged', e.value));

let animating = timescope.animating;
let editing = timescope.editing;
timescope.on('change', () => {
  if (timescope.animating !== animating) {
    animating = timescope.animating;
    emit('animating', animating);
  }
  if (timescope.editing !== editing) {
    editing = timescope.editing;
    emit('editing', editing);
  }
});

timescope.on('timechanged', (e) => emit('update:time', e.value));
timescope.on('zoomchanged', (e) => emit('update:zoom', e.value));
timescope.on('timechanging', (e) => emit('update:timechanging', e.value));
timescope.on('zoomchanging', (e) => emit('update:zoomchanging', e.value));
timescope.on('timeanimating', (e) => emit('update:timeanimating', e.value));
timescope.on('zoomanimating', (e) => emit('update:zoomanimating', e.value));
timescope.on('selectedrangechanging', (e) => emit('update:selectedrangechanging', e.value));
timescope.on('selectedrangechanged', (e) => emit('update:selectedrange', e.value));

if (props.time === undefined) {
  emit('update:time', timescope.time);
  emit('update:timechanging', timescope.time);
  emit('update:timeanimating', timescope.time);
}
if (props.zoom === undefined) {
  emit('update:zoom', timescope.zoom);
  emit('update:zoomchanging', timescope.zoom);
  emit('update:zoomanimating', timescope.zoom);
}

watch(
  () => props.time,
  () => timescope?.setTime(props.time ?? null),
);
watch(
  () => props.timeRange,
  () => timescope?.setTimeRange(props.timeRange),
);
watch(
  () => props.zoom,
  () => timescope?.setZoom(props.zoom ?? 0),
);
watch(
  () => props.zoomRange,
  () => timescope?.setZoomRange(props.zoomRange),
);

watch(
  () => [props.width, props.height, props.background],
  () => timescope.updateOptions({ style: { width: props.width, height: props.height, background: props.background } }),
  { immediate: true },
);

watch(
  () => props.sources,
  () => timescope.updateOptions({ sources: props.sources } as TimescopeOptions),
  { immediate: true, deep: true },
);

watch(
  () => props.series,
  () => timescope.updateOptions({ series: props.series } as TimescopeOptions),
  { immediate: true, deep: true },
);

watch(
  () => props.tracks,
  () => timescope.updateOptions({ tracks: props.tracks } as TimescopeOptions),
  { immediate: true, deep: true },
);

watch(
  () => props.indicator,
  () => timescope.updateOptions({ indicator: props.indicator } as TimescopeOptions),
  { immediate: true, deep: true },
);

watch(
  () => props.selection,
  () => timescope.updateOptions({ selection: props.selection } as TimescopeOptions),
  { immediate: true, deep: true },
);

watch(
  () => props.showFps,
  () => timescope.updateOptions({ showFps: props.showFps } as TimescopeOptions),
  { immediate: true },
);

const el = useTemplateRef('container-ref');

watch(el, () => {
  timescope?.unmount();
  if (el.value) timescope?.mount(el.value);
});

onBeforeUnmount(() => {
  timescope?.dispose();
});

</script>
