// packages/timescope-svelte/App.svelte
<script lang="ts">
  import { Timescope } from '@timescope/svelte';
  import type { Decimal } from '@timescope/svelte';
  import type { TimescopeRange } from 'timescope';

  let time: Decimal | null = null;
  let timeChanging: Decimal | null = null;
  let timeAnimating: Decimal | null = null;
  let selectedRangeChanging: TimescopeRange<Decimal> | null = null;
</script>

<Timescope
  bind:time
  on:timechanging={(e) => (timeChanging = e.detail)}
  on:timeanimating={(e) => (timeAnimating = e.detail)}
  on:selectedrangechanging={(e) => (selectedRangeChanging = e.detail)} />

<pre>time: {time?.toString()}</pre>
<pre>timeChanging: {timeChanging?.toString()}</pre>
<pre>timeAnimating: {timeAnimating?.toString()}</pre>
<pre>selectedRangeChanging: {selectedRangeChanging?.toString()}</pre>

// packages/timescope-react/App.tsx
import { Decimal, Timescope } from '@timescope/react';
import { useState } from 'react';
import { type TimescopeRange } from 'timescope';

function App() {
  const [time, setTime] = useState<Decimal | null>(null);
  const [timeChanging, setTimeChanging] = useState<Decimal | null>(null);
  const [timeAnimating, setTimeAnimating] = useState<Decimal | null>(null);
  const [selectedRangeChanging, setSelectedRangeChanging] = useState<TimescopeRange<Decimal> | null>(null);

  return (
    <>
      <Timescope
        time={time}
        onTimeChanged={setTime}
        onTimeChanging={setTimeChanging}
        onTimeAnimating={setTimeAnimating}
        onSelectedRangeChanging={setSelectedRangeChanging}
      />
      <pre>time: {time?.toString()}</pre>
      <pre>timeChanging: {timeChanging?.toString()}</pre>
      <pre>timeAnimating: {timeAnimating?.toString()}</pre>
      <pre>selectedRangeChanging: {selectedRangeChanging?.toString()}</pre>
    </>
  );
}

export default App;
